### PR TITLE
Optional TCP MSS option (--tcpmss)

### PR DESCRIPTION
**Pull request by mzpqnxow**
There was a discussion about this a while back (https://github.com/robertdavidgraham/masscan/pull/326) and I ended up needing to add this for a few specific networks that appear to be deliberately dropping packets without TCP options. This is open upstream as https://github.com/robertdavidgraham/masscan/pull/646

Please feel free to rework it into something a little bit neater if you do want to merge it

### CODE REVIEW

**Comment by mzpqnxow** [comment]
Also, any thoughts on making it an option to set the MSS to an arbitrary value?

I figure the objective is to blend to make surveys more accurate rather than to allow a user to fully customize the packet (and that can become a very slippery slope ...) so I decided not to make the MSS value customizable

**Comment by p-l-** [comment]
@mzpqnxow I'm so sorry I wasn't, for some reason, watching this repository :-/

I'll look at your PR ASAP.

**Comment by p-l-** [comment]
I have a request (I can take care of it if you want): could you amend your commits to remove unneeded changes (like spaces / newlines in `src/templ-pkt.c`)? It will be much easier for me to keep this repository synchronized with its upstream.

**Comment by mzpqnxow** [comment]
Hey, sorry for the slow response- not sure if you already made the changes yourself but I think I cleaned up what you were referring to

**Comment by p-l-** [comment]
I did some more fixes in `src/templ-pkt.c` because you had added / removed whitespaces while it was not needed, and that makes it harder for me to maintain the patch. Your commit has now also been rebased so that the `README.md` is updated in the last commit.

Thanks for this contribution!

**Comment by mzpqnxow** [comment]
Great, thanks- and apologies, that whitespace wasn't deliberate- I actually had a hard time spotting it at first, even after you pointed it out- good eye, though I guess it stands out when you try to merge/sync with upstream

Also, thanks for merging, you've become my official upstream, though I'm not (yet) a user of IVRE

**Comment by p-l-** [comment]
If you are a user of the `--banners` option, you may like @Frky's PR (robertdavidgraham/masscan#681) that is also integrated here (with a fix that @Frky needs to add in his PR to the official project).

If you do not use IVRE to parse the results, you may have useless values, for example, with SSH servers. Having users of this project who don't use IVRE was not my target, but if you tell me what your issues are, we'll do our best to help you.

**Pull request merged**
